#
# 
# ShowErrorsInClient: toggle that determines if permissions or other error messages
#                     are displayed client-side
#
# Allowed values : Yes (shows errors to players)
#                  No  (errors only show up in server console)
# 
ShowErrorsInClient: Yes

#
#
# AllowedTreeTypes: list of items that can be planted in soil(aka farmland)
#
# Examples: "apple", "golden_apple", "cookie", "pork", "cocoa_beans"
#
AllowedTreeTypes:
    - "apple"
    - "cocoa_beans"

#
#
# DropsContinuous: determines if drops should happen forever, or until a tree gets "tired"
#                  and requires bonemeal fertilizer.  
#
# Allowed values : Yes (drops happen at inteverals forever)
#                  No  (trees get tired and require bonemeal to fertilize them)
#
DropsContinuous: Yes

#
# 
# DropLikelihood: percentage chance an item will drop under a tree
#
# Allowed values: numbers 1 through 100 (no decimals)
#                  100 means items will spawn every interval
#                  1 means items will spawn once out of every hundred intervals
# 
DropLikelihood: 33

#
# 
# DropInterval: length of time, in seconds, between drops
#
# Allowed values: numbers bigger than 1 (no decimals)
# 
DropInterval: 60

#
# 
# DropsBeforeTired: approximate number of drops before a tree gets tired
#
# Allowed values: numbers bigger than 1 (no decimals)
# 
DropsBeforeTired: 100
