#
# ShowErrorsInClient: toggle that determines if permissions or other error messages
#                     are displayed client-side
#
# Allowed values : Yes (shows errors to players)
#                  No  (errors only show up in server console)
# 
ShowErrorsInClient: Yes

#
# DropInterval: length of time, in seconds, between drops
#
# Allowed values: numbers bigger than 1 (no decimals)
# 
DropInterval: 60

#
# WandItem: item used in game to see what type a tree is and if it needs fertilizer 
#
# Allowed values: any decimal item id (default is 290 for wooden hoe)
# 
WandItem: 290

#
# MinimumTreeDistance: optional parameter specifies minimum block distance between planted trees 
#
# Allowed values: any decimal number bigger than 1 (set to -1 to disable, or comment out the parameter)
# 
#MinimumTreeDistance: 8

#
#
# TreeTypes: list of items that can be planted in soil(aka farmland)
#
# Example: 
#    - "apple"                      # Name of the item that must be planted and will be dropped
#        DropLikelihood: 33         # Chance an item will drop under a tree (numbers 1-100)
#        RequireFertilzer: Yes      # Yes if the tree should require occasional fertilizer
#        DropsBeforeFertilzer: 50   # Approximate number of drops before fertilzer is required
#        MaxFertilizer: 5            # Approximate number of times a tree can be fertilized (optional, or set to -1 to disable)
#        TreeType: Standard         # Type of tree that should grow from the sapling (Standard/Spruce/Birch)
#
TreeTypes:
    apple:
        DropLikelihood: 33
        RequireFertilzer: Yes
        DropsBeforeFertilzer: 50
#        MaxFertilizer: 10
        TreeType: Standard
        
    cocoa_beans:
        DropLikelihood: 33
        RequireFertilzer: Yes
        DropsBeforeFertilzer: 50
#        MaxFertilizer: 10
        TreeType: Spruce

    golden_apple:
        DropLikelihood: 5
        RequireFertilzer: Yes
        DropsBeforeFertilzer: 10
        MaxFertilizer: 5
        TreeType: Birch

    cookie:
        DropLikelihood: 33
        RequireFertilzer: Yes
        DropsBeforeFertilzer: 50
#        MaxFertilizer: 5
        TreeType: Standard
